# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
tableRcpp <- function(x) {
    .Call('_BrazilSaltModelmisc_tableRcpp', PACKAGE = 'BrazilSaltModelmisc', x)
}

#' @export
counts <- function(x) {
    .Call('_BrazilSaltModelmisc_counts', PACKAGE = 'BrazilSaltModelmisc', x)
}

#' @export
fquantile <- function(x, probs, na_rm = TRUE) {
    .Call('_BrazilSaltModelmisc_fquantile', PACKAGE = 'BrazilSaltModelmisc', x, probs, na_rm)
}

#' @export
fquantile_byid <- function(x, q, id, rounding = FALSE, na_rm = TRUE) {
    .Call('_BrazilSaltModelmisc_fquantile_byid', PACKAGE = 'BrazilSaltModelmisc', x, q, id, rounding, na_rm)
}

#' @export
fbound <- function(x, a, b) {
    .Call('_BrazilSaltModelmisc_fbound', PACKAGE = 'BrazilSaltModelmisc', x, a, b)
}

#' @export
fbound_int <- function(x, a, b) {
    .Call('_BrazilSaltModelmisc_fbound_int', PACKAGE = 'BrazilSaltModelmisc', x, a, b)
}

#' @export
fbound_inplace <- function(x, a, b) {
    .Call('_BrazilSaltModelmisc_fbound_inplace', PACKAGE = 'BrazilSaltModelmisc', x, a, b)
}

#' @export
fbound_inplace_int <- function(x, a, b) {
    .Call('_BrazilSaltModelmisc_fbound_inplace_int', PACKAGE = 'BrazilSaltModelmisc', x, a, b)
}

#' @export
fequal <- function(x, tol) {
    .Call('_BrazilSaltModelmisc_fequal', PACKAGE = 'BrazilSaltModelmisc', x, tol)
}

#' @export
fnormalise <- function(x) {
    .Call('_BrazilSaltModelmisc_fnormalise', PACKAGE = 'BrazilSaltModelmisc', x)
}

#' @export
fcompress <- function(x, limit) {
    .Call('_BrazilSaltModelmisc_fcompress', PACKAGE = 'BrazilSaltModelmisc', x, limit)
}

#' @export
roll_mean_left <- function(dat, window) {
    .Call('_BrazilSaltModelmisc_roll_mean_left', PACKAGE = 'BrazilSaltModelmisc', dat, window)
}

#' @export
shift_byidNum <- function(x, lag, replace, id) {
    .Call('_BrazilSaltModelmisc_shift_byidNum', PACKAGE = 'BrazilSaltModelmisc', x, lag, replace, id)
}

#' @export
shift_byidInt <- function(x, lag, replace, id) {
    .Call('_BrazilSaltModelmisc_shift_byidInt', PACKAGE = 'BrazilSaltModelmisc', x, lag, replace, id)
}

#' @export
shift_byidStr <- function(x, lag, replace, id) {
    .Call('_BrazilSaltModelmisc_shift_byidStr', PACKAGE = 'BrazilSaltModelmisc', x, lag, replace, id)
}

#' @export
sort_byidInt <- function(x, id) {
    .Call('_BrazilSaltModelmisc_sort_byidInt', PACKAGE = 'BrazilSaltModelmisc', x, id)
}

#' @export
sort_byidNum <- function(x, id) {
    .Call('_BrazilSaltModelmisc_sort_byidNum', PACKAGE = 'BrazilSaltModelmisc', x, id)
}

#' @export
df2mat_numeric <- function(x) {
    .Call('_BrazilSaltModelmisc_df2mat_numeric', PACKAGE = 'BrazilSaltModelmisc', x)
}

#' @export
df2mat_integer <- function(x) {
    .Call('_BrazilSaltModelmisc_df2mat_integer', PACKAGE = 'BrazilSaltModelmisc', x)
}

#' @export
collect_output <- function(m1, m2, m3, d1, p1, p2, p3, id) {
    .Call('_BrazilSaltModelmisc_collect_output', PACKAGE = 'BrazilSaltModelmisc', m1, m2, m3, d1, p1, p2, p3, id)
}

#' @export
my_pBCPEo <- function(q, mu, sigma, nu, tau, n_cpu) {
    .Call('_BrazilSaltModelmisc_my_pBCPEo', PACKAGE = 'BrazilSaltModelmisc', q, mu, sigma, nu, tau, n_cpu)
}

#' @export
my_qBCPEo <- function(p, mu, sigma, nu, tau, n_cpu) {
    .Call('_BrazilSaltModelmisc_my_qBCPEo', PACKAGE = 'BrazilSaltModelmisc', p, mu, sigma, nu, tau, n_cpu)
}

#' @export
my_qBCPEo_trunc <- function(p, mu, sigma, nu, tau, lower_lim, upper_lim, n_cpu) {
    .Call('_BrazilSaltModelmisc_my_qBCPEo_trunc', PACKAGE = 'BrazilSaltModelmisc', p, mu, sigma, nu, tau, lower_lim, upper_lim, n_cpu)
}

#' @export
my_pBCT <- function(q, mu, sigma, nu, tau, n_cpu) {
    .Call('_BrazilSaltModelmisc_my_pBCT', PACKAGE = 'BrazilSaltModelmisc', q, mu, sigma, nu, tau, n_cpu)
}

#' @export
my_qBCT <- function(p, mu, sigma, nu, tau, n_cpu) {
    .Call('_BrazilSaltModelmisc_my_qBCT', PACKAGE = 'BrazilSaltModelmisc', p, mu, sigma, nu, tau, n_cpu)
}

#' @export
my_qBCT_trunc <- function(p, mu, sigma, nu, tau, lower_lim, upper_lim, n_cpu) {
    .Call('_BrazilSaltModelmisc_my_qBCT_trunc', PACKAGE = 'BrazilSaltModelmisc', p, mu, sigma, nu, tau, lower_lim, upper_lim, n_cpu)
}

#' @export
my_runif_seeded <- function(n, lower_bound, upper_bound, seed) {
    .Call('_BrazilSaltModelmisc_my_runif_seeded', PACKAGE = 'BrazilSaltModelmisc', n, lower_bound, upper_bound, seed)
}

#' @export
my_runif <- function(n, lower_bound, upper_bound) {
    .Call('_BrazilSaltModelmisc_my_runif', PACKAGE = 'BrazilSaltModelmisc', n, lower_bound, upper_bound)
}

#' @export
mk_new_simulant_markers <- function(pid) {
    .Call('_BrazilSaltModelmisc_mk_new_simulant_markers', PACKAGE = 'BrazilSaltModelmisc', pid)
}

#' @export
incidence_type_1 <- function(year, is_new_simulant, prob, prevalence, init_year) {
    .Call('_BrazilSaltModelmisc_incidence_type_1', PACKAGE = 'BrazilSaltModelmisc', year, is_new_simulant, prob, prevalence, init_year)
}

#' @export
incidence_type_2 <- function(year, is_new_simulant, prob, rn, prevalence, init_year) {
    .Call('_BrazilSaltModelmisc_incidence_type_2', PACKAGE = 'BrazilSaltModelmisc', year, is_new_simulant, prob, rn, prevalence, init_year)
}

#' @export
incidence_type_3 <- function(year, is_new_simulant, t2dm_prob, t2dm_rn, t2dm_prvl, t2dm_cvd_multiplier, chd_prob, chd_rn, chd_prvl, stroke_prob, stroke_rn, stroke_prvl, cvd_t2dm_multiplier, t2dm_lag, cvd_lag, init_year) {
    .Call('_BrazilSaltModelmisc_incidence_type_3', PACKAGE = 'BrazilSaltModelmisc', year, is_new_simulant, t2dm_prob, t2dm_rn, t2dm_prvl, t2dm_cvd_multiplier, chd_prob, chd_rn, chd_prvl, stroke_prob, stroke_rn, stroke_prvl, cvd_t2dm_multiplier, t2dm_lag, cvd_lag, init_year)
}

#' @export
mortality_type_1 <- function(year, is_new_simulant, prob, rn, prevalence, init_year, cod) {
    .Call('_BrazilSaltModelmisc_mortality_type_1', PACKAGE = 'BrazilSaltModelmisc', year, is_new_simulant, prob, rn, prevalence, init_year, cod)
}

#' @export
mortality_type_2 <- function(year, is_new_simulant, prob, rn, diagnosed, prevalence, init_year, cod, cure) {
    .Call('_BrazilSaltModelmisc_mortality_type_2', PACKAGE = 'BrazilSaltModelmisc', year, is_new_simulant, prob, rn, diagnosed, prevalence, init_year, cod, cure)
}

#' @export
mortality_resolve <- function(year, is_new_simulant, cod1, cod2, cod3, rn, init_year) {
    .Call('_BrazilSaltModelmisc_mortality_resolve', PACKAGE = 'BrazilSaltModelmisc', year, is_new_simulant, cod1, cod2, cod3, rn, init_year)
}

#' @export
morbidity_resolve <- function(year, disease1, disease2, death, disease_names, cod_names, init_year) {
    .Call('_BrazilSaltModelmisc_morbidity_resolve', PACKAGE = 'BrazilSaltModelmisc', year, disease1, disease2, death, disease_names, cod_names, init_year)
}

#' @export
count_if <- function(x, na_rm = FALSE) {
    .Call('_BrazilSaltModelmisc_count_if', PACKAGE = 'BrazilSaltModelmisc', x, na_rm)
}

#' @export
prop_if <- function(x, na_rm = FALSE) {
    .Call('_BrazilSaltModelmisc_prop_if', PACKAGE = 'BrazilSaltModelmisc', x, na_rm)
}

#' @export
fscramble_trajectories <- function(x, pid, jump) {
    .Call('_BrazilSaltModelmisc_fscramble_trajectories', PACKAGE = 'BrazilSaltModelmisc', x, pid, jump)
}

#' @export
identify_longdeads <- function(x, pid) {
    .Call('_BrazilSaltModelmisc_identify_longdeads', PACKAGE = 'BrazilSaltModelmisc', x, pid)
}

